# Generated by Django 5.0.2 on 2024-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaqolaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('source', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('description_uzb', models.TextField(blank=True, null=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, choices=[('Certificates', 'Certificates'), ('Projects', 'Projects'), ('Education', 'Education')], max_length=255, null=True)),
            ],
        ),
    ]
