# Generated by Django 5.1.4 on 2025-01-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingAdvicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.TextField(blank=True, null=True)),
                ('uzb', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
